### ISSUE TITLE
[bug反馈]用文档的示例测试失败

### ISSUE THREAD

**Issue by daofeng2015** [wdvxdr1123/ZeroBot#12]
![image](https://user-images.githubusercontent.com/14891398/105167824-2e791600-5b54-11eb-8857-646edc67def3.png)
版本信息:
![QQ截图20210120191810](https://user-images.githubusercontent.com/14891398/105167972-684a1c80-5b54-11eb-8c6b-1990e1168b63.png)

**Comment by wdvxdr1123** [comment]
因为是 OnCommand 所以触发指令需要前缀

**Comment by wdvxdr1123** [comment]
根据你设置的 CommandPrefix, 比如example中为 “/”， 你需要使用"/开启复读"
