### ISSUE TITLE
求求大佬做个文档吧！！！！硬啃源码吃不等动啦QWQ

### ISSUE THREAD

**Issue by LingMuXing** [wdvxdr1123/ZeroBot#19]
我太难了QWQ

**Comment by YumeMichi** [comment]
纳尼 example里有示例

**Comment by LingMuXing** [comment]
学废了jpg&nbsp;
更多的其它用法看不懂需要不停的试qwq
摸索中jpg









GM

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月2日(周三) 晚上6:06
收件人: ***@***.***&gt;;
抄送: "林沐馨"<1534373314@***@***.***&gt;;
主题: Re: [wdvxdr1123/ZeroBot] 求求大佬做个文档吧！！！！硬啃源码吃不等动啦QWQ (#19)




 
纳尼 example里有示例
