### ISSUE TITLE
连客户端与服务端的连接配置介绍都没有，测试半天都不知道怎么连接上去

### ISSUE THREAD

**Issue by wordgao** [wdvxdr1123/ZeroBot#20]
如题。

**Comment by wdvxdr1123** [comment]
采用正向WS连接
可参考 https://github.com/wdvxdr1123/ZeroBot/blob/main/example/main.go#L28
onebot端配置 开启正向ws，端口6700

**Comment by wordgao** [comment]
非常感谢，已测试连接成功了。
