### ISSUE TITLE
请问group at如何操作

### ISSUE THREAD

**Issue by wordgao** [wdvxdr1123/ZeroBot#23]
比如非好友状态的情况下，我想@某个成员，如何操作。

**Comment by wdvxdr1123** [comment]
可以用 `message.At(qq)`， at全体可以用`message.At(0)`

**Comment by wordgao** [comment]
感谢。

**Comment by wordgao** [comment]
是不是应该加一个 
message.At(qq int64, msg interface())

**Comment by wdvxdr1123** [comment]
`message.Message{messafe.At(qq), messafe.Text(text)}`

**Comment by wordgao** [comment]
感谢，稍后我试试。

**Comment by wordgao** [comment]
给下具体的操作步骤，是怎么发出去的，谢谢了。

**Comment by wdvxdr1123** [comment]
```go
ctx.Send(message.Message{messafe.At(123456), messafe.Text("654321")})
```
or
```go
ctx.SendChain(messafe.At(123456), messafe.Text("654321"))
```

**Comment by wordgao** [comment]
messafe.At 中的messafe是什么类型的安全模式，还是说 是使用message包里面的message.At

**Comment by wordgao** [comment]
现在好像连测试的机会都没有的，因为最新规则是 只要数据发送就会校验信息格式与参数是否正确，否则就会被风控。现在好几个Q都被风控了，测试都没机会测试。

**Comment by wordgao** [comment]
ctx.Send(message.Message{message.At(ctx.Event.UserID), message.Text(ctx.Event.RawMessage)})
 测试直接被风控了。

**Comment by wordgao** [comment]
![image](https://user-images.githubusercontent.com/10544395/126740726-f9c46478-3c07-450b-a7ab-d72ad534e64b.png)

**Comment by wdvxdr1123** [comment]
`messafe`是打错了，:joy:

**Comment by wordgao** [comment]
😂

**Comment by wordgao** [comment]
留个email咨询一下或直接发邮件给我 wordgao@gmail.com

**Comment by wdvxdr1123** [comment]
可以加gocqhttp交流群 721829413
