### ISSUE TITLE
请问如何不经由 Bot 的事件驱动发送消息？

### ISSUE THREAD

**Issue by yifanc62** [wdvxdr1123/ZeroBot#28]
场景可以大致抽象为我有一个 MQ，需要在收到 MQ 事件回调的时候发送消息，而不是通过 `On` 来注册事件回调。这时我没有 `Ctx` 上下文，请问我该如何通过现有的 WS 连接发送一个 Payload？

**Comment by yifanc62** [comment]
已在讨论群组解决，方法为 `zero.GetBot`

**Comment by ctaoist** [comment]
请问一下，getbot的参数是什么，qq号？我试了好像不行
