### ISSUE TITLE
如何使用定时任务

### ISSUE THREAD

**Issue by RedElectricity** [wdvxdr1123/ZeroBot#29]
是这样子的,我想写个RSS功能,是一个定时任务,但是怎么样直接用函数发送

**Comment by wdvxdr1123** [comment]
https://pkg.go.dev/github.com/wdvxdr1123/ZeroBot#GetBot

https://pkg.go.dev/github.com/wdvxdr1123/ZeroBot#RangeBot

注意获取到的 Ctx 无Event字段， 请不要使用Send/ SendChain发送消息， 使用 SendGroupMessage

**Comment by RedElectricity** [comment]
我想再问一个问题,虽然和这个topic有点无关了

发送消息能使用cq码发送吗?message chain有点麻烦
