### ISSUE TITLE
能否将OnCommand中的指令匹配改为正则

### ISSUE THREAD

**Issue by yuyuko233** [wdvxdr1123/ZeroBot#66]
能否将`OnCommand`中的指令匹配改为正则

例如 [Shiro](https://github.com/MisakaTAT/Shiro) 框架的匹配指令

![图片](https://user-images.githubusercontent.com/20128226/179351184-7f242670-19d9-4ba1-b24d-ce00f2de416b.png)
![图片](https://user-images.githubusercontent.com/20128226/179351196-236c419c-5246-4be8-a7d7-7616798792be.png)

**Comment by fumiama** [comment]
直接使用OnRegex即可。
