### ISSUE TITLE
处理是否at机器人时，跳过了at的Message，导致后面获取不到at谁的原信息

### ISSUE THREAD

**Issue by Hamusuta0320** [wdvxdr1123/ZeroBot#70]
我想在我的程序中获取消息艾特的对象，但是无法获取到，断点调试后发现在处理是否at机器人的时候将这条消息跳过了，不明白此处的用意，请问是我使用的方法有问题吗
![image](https://user-images.githubusercontent.com/55654842/205368467-1a757d6f-5c87-4b10-b4b9-b81f075ade75.png)

**Comment by fumiama** [comment]
bot会删除针对自己的 @ , 但是不会删除针对他人的。这是特性不是bug😂。如果想得知是否 @ 自己，可以使用`IsToMe`

**Comment by Hamusuta0320** [comment]
> bot会删除针对自己的 @ , 但是不会删除针对他人的。这是特性不是bug😂。如果想得知是否 @ 自己，可以使用`IsToMe`

现在明白了 谢谢大佬解答！

**Comment by JHue58** [comment]
删除了@自己的消息后，还有办法得知"@自己"这条消息处于消息链的哪个位置吗？
比如A发了一条消息"/do @B @Bot @C"
插件的逻辑需要处理[B的qq，Bot的qq，C的qq]这样一个有序的队列
