### ISSUE TITLE
无法接收禁言机器人的notice

### ISSUE THREAD

**Issue by alexskim** [wdvxdr1123/ZeroBot#72]
相关代码,别人被禁言可以正常触发,gocqhttp中有机器人被禁言的提示。
![image](https://user-images.githubusercontent.com/21965001/206987738-640cd28e-9b57-489a-b9e6-331ff3ab08a4.png)
使用这种方式产生的结果一致,加上zero.OnlyToMe也一样。
![image](https://user-images.githubusercontent.com/21965001/206991981-21872693-acb7-442b-8e11-08032d11245b.png)

**Comment by fumiama** [comment]
请开debug模式给出notice的json事件。zb本身并未限制接收这类事件。如果你正在使用zbp，那么可能是这里的逻辑阻止了接收。

https://github.com/FloatTech/zbputils/blob/main/control/engine.go#L35-L41

**Comment by alexskim** [comment]
![image](https://user-images.githubusercontent.com/21965001/206996506-baa7e52a-5c4b-42f2-8d85-544b36d29fc8.png)
使用的是zbp,根据json来看,确实是那一段代码阻止了,那么有办法实现接收机器人被禁言的notice吗

**Comment by alexskim** [comment]
我自己试了一下,直接使用zerobot可以接收到

**Comment by fumiama** [comment]
是的。你可以使用zero.OnNotice替代engine。
