### ISSUE TITLE
zero.OnCommand will handle other command.

### ISSUE THREAD

**Issue by Dreamail** [wdvxdr1123/ZeroBot#76]
e.g.
zero.OnCommand("bind") will handle zero.OnCommand("bindx") at the same time.

**Comment by fumiama** [comment]
Well, that's a feature 😂. Seealso #38 #39 #40

**Comment by Dreamail** [comment]
Are you serious?
It should not act like this.

**Comment by fumiama** [comment]
I'm serious. There're many ways that are able to avoid the duplicated command prefix. Actually it is designed for Chinese commands like `/启动abc`. You don't need to add a space between them.

**Comment by Dreamail** [comment]
Oh, for Chinese, it makes sense.
