### ISSUE TITLE
delete_msg Action 不符合规范

### ISSUE THREAD

**Issue by yuanzui-cf** [wdvxdr1123/ZeroBot#81]
OneBot 11 的规范要求 (https://github.com/botuniverse/onebot-11/blob/master/api/public.md#delete_msg-%E6%92%A4%E5%9B%9E%E6%B6%88%E6%81%AF) 是 message_id 传入 number，但是 ZeroBot 传入了 messageID.String()

![image](https://github.com/user-attachments/assets/92048b31-6dcf-4017-9f1d-9b15a9dee18a)

![image](https://github.com/user-attachments/assets/d89f3ec8-cd99-43ee-b692-2d44bf9fcf02)

**Comment by yuanzui-cf** [comment]
> 因为这个经过了扩展，支持了频道的message id，而频道的id是string。

频道撤回能不能单独开一个函数，部分框架（[NapCat](https://github.com/NapNeko/NapCatQQ)）严格按照文档，不接受字符串的 message_id

**Comment by fumiama** [comment]
可以修一下，毕竟现在频道不是主流而且没有规范。

**Comment by fumiama** [comment]
不对，你同步最新就可以了，最新用的不是string，而是可以自定义任意类型，当然也包括int。

https://github.com/wdvxdr1123/ZeroBot/blob/3ff3d73940da8a53f5993c2ce880da3b124430c9/api.go#L96-L104
