### ISSUE TITLE
如何知道"@自己"这条at信息处于消息链的哪个位置？

### ISSUE THREAD

**Issue by JHue58** [wdvxdr1123/ZeroBot#92]
https://github.com/wdvxdr1123/ZeroBot/issues/70
删除了@自己的消息后，还有办法得知"@自己"这条消息处于消息链的哪个位置吗？
比如A发了一条消息"/do @B @Bot @C"
插件的逻辑需要处理[B的qq，Bot的qq，C的qq]这样一个有序的队列

**Comment by fumiama** [comment]
目前不行。

**Comment by Azusa-Yuan** [comment]
多个@bot 只会删一个，或许可以用@bot 两次来解决这种需求
